data-engineering-team4/Lulu

- src/airflow/dags/utils/common_util.py
- **한국 시간이 지정되지 않으면, S3 측에서 UTC 기준으로 저장된다고 합니다.**
- 때문에 pendulum.datetime 라이브러리로 불러서 시간대 처리를 해줘야 합니다.
```python
NOW = get_current_datetime()
YMD = get_formatted_date(NOW)
TIMESTAMP = get_formatted_timestamp(NOW)
```
- Closes #
> feat: common_util 생성

- src/airflow/dags/get_high_elo_summoner_dag.py
- src/airflow/dags/get_match_list_dag.py
- src/airflow/dags/get_summoner_puuid_dag.py
- src/airflow/dags/utils/common_util.py
- src/airflow/dags/utils/riot_util.py
- get_high_elo_summoner_dag, get_summoner_puuid_dag, get_match_list_dag 수정
- 특정 부분에서 문제가 발생하여 팀원들과 함께 검토 필요
이 PR은 아직 완료되지 않았으며 팀원들과 함께 문제를 해결하기 위해 작성되었습니다. 리뷰와 피드백 부탁드립니다.
- Related Issue #15 #16 
- Closes #
> wip: 작업 중인 기능 개선 (#15, #16)

- .github/workflows/ci/black.yml
- .github/workflows/ci/flake8.yml
flake8: main 브랜치에 pr이 올라올 때 마다 검사 
black: develop 브랜치에 push할 때 마다 검사
- Related Issue #34 
- Closes #34 
ci 기능 특성상 아직 테스트를 못해봤습니다.
기존 코드도 리팩토링 해봅시다!
> CI: flake8 and Black code checks

- Dockerfile
- src/airflow/dags/get_riot_api_dag.py
- start-airflow.sh
> feat: DockerFile 추가

- docker-compose/docker-compose.yml
- src/airflow/dags/get_riot_api_dag.py
- src/backend/app.py
-all_data_1, all_data_2, all_data_3 redis 삭제 
-time.sleep(1.2)를 limiter로 대체하였습니다.
- Related Issue #42 #44 
- Closes #42 #44 
잘 작동중입니다. 테스트는 10시간 이내로 끝날 것 같습니다.
기존 코드 대비 2배정도 속도 향상이 있습니다.
docker compose down up 다시 해야합니다!
> fix: delete redis key bug

- requirements.txt
- src/airflow/Dockerfile
- src/airflow/config/airflow.cfg
- src/airflow/config/entrypoint.sh
- src/airflow/dags/utils/common_util.py
- src/airflow/requirements.txt
- **Dockerfile**: 애플리케이션의 컨테이너화를 위한 Docker 파일을 추가
- **requirements.txt**: 필요한 파이썬 패키지 목록 수정
- **airflow.cfg**: Airflow 설정을 업데이트하여 최적의 구성 제공
- **entrypoint.sh**: 컨테이너가 시작될 때 실행되는 초기화 스크립트
- **generate_fernet_key function**: common_util.py에 추가 (Airflow의 보안 향상을 위해 Fernet 키 생성)
- Related Issue #45 
- Closes #45
> feat: 도커 설정 파일 및 fernet 키 발급 함수 추가 

- src/backend/app.py
- src/backend/app/dependencies.py
- src/backend/app/main.py
- src/backend/app/routers/summoners.py
- **app**: 주 어플리케이션 디렉토리
- **internal**: 내부 모듈 및 컴포넌트용
- **routers**: 라우팅 로직을 처리하기 위함
- **models**: 데이터베이스 모델 및 스키마용
- **utils**: 유틸리티 함수와 공통 헬퍼용
- **tests**: 테스트 케이스와 관련 기능을 포함하기 위함
- Related Issue #58 
- Closes #58 
```python
uvicorn app.main:app --reload
```
> feat: Fast API 기본 구조 생성

- src/airflow/dags/get_riot_api_dag.py
- champion_ban 컬럼 추가했습니다.
- Related Issue #9 
- Closes #
> feat: 데이터셋에 bans 컬럼 추가

- src/airflow/dags/mastery_sample1.py
- src/airflow/dags/mastery_sample2.py
- mastery_sample1.py(sklearn의 코사인 유사도 사용) 추가
- mastery_sample2.py(spark의 ml(kmeans) 사용) 추가
- Related Issue #49 
- Closes #
Name: Jinx, dtype: float64
Kai'Sa     0.479895
Xayah      0.478487
Ezreal     0.464217
Sivir      0.443310
Caitlyn    0.442653
Lucian     0.434319
Vayne      0.431984
Varus      0.389124
Jhin       0.378527
Ashe       0.364808
- mastery_sample1.py은 데이터를 많이 쌓아서 돌려야 효율적
- mastery_sample2.py는 모델을 만들어 학습시키고 필터링으로 비슷한 유저를 찾아주는 데 특화
- 분석은 api 호출이랑 다르게 시간이 오래 걸리지는 않아서 같이 생각해보고 방식을 정하는 게 더 좋을 것 같습니다!
> test: 숙련도 관련 테스트 파일 추가

- .github/workflows/deploy-to-ecr-and-ecs.yml
- 워크플로우가 `main` 브랜치에서만 실행되도록 설정
- 워크플로우가 `src/airflow/**` 경로의 변경에서만 실행되도록 설정
- 워크플로우가 원본 리포지토리에서만 실행되도록 조건 추가
- Related Issue #50 
- Closes #
> chore: 배포 워크플로우 브랜치 제한

- src/airflow/dags/get_riot_api_dag.py
logging을 100건, 1000건마다 기록
try, except 추가, time limit 추가
champion_id 버그 해결
get_mastery concat -> list.append 리팩토링
- Related Issue #57 
- Closes #
테스트는 못해봤습니다.
우선 수정했는데 또 버그가 생기면 57번 이슈에 계속 수정합시다!
> fix: dag 파일 수정

- src/backend/app/db_session.py
- src/backend/app/main.py
- src/backend/app/models/summoner.py
- src/backend/app/routers/banpick.py
- src/backend/app/utils/consumer_test.py
- src/backend/requirements.txt
백엔드, 프론트엔드, 카프카, aws rds 서버들을 연결하는 작업입니다.
- Related Issue #80 #81 #84 
- Closes #80 #81 #84
> feat: 배포된 서버들을 연결하는 작업

- .github/workflows/deploy-backend.yml
- .github/workflows/deploy-frontend.yml
백엔드: main src/backend에 코드가 push 될 때마다 elastic beanstalk에 deploy
프론트엔드: main src/frontend에 코드가 push 될 때마다 s3, cloudfront에 update
- Related Issue #83
- Closes #83
CI는 테스트코드 생기면 그때 추가하겠습니다.
> Web sever CI/CD

- docker-compose/docker-compose.yml
- src/airflow/dags/get_mastery_dag.py
- docker-compose파일에 scikit-learn이랑 pymysql 설치 코드 추가
- get_mastery_dag 완성
- Related Issue #49 
- Closes #
- 로컬에서는 docker-compose파일을 고쳐서 상관없는데 ECR에 올릴 때는 requirements.txt에 scikit-learn이랑 pymysql 추가해야합니다.(사실 제가 추가할까 했는데 requirements.txt가 2개 있어서 어디 추가해야 하는지 잘 모르겠어서...)
- 또한, airflow의 variable에 정보 입력해야 합니다(Slack으로 공유 예정)
> feat: 숙련도 분석 dag 추가

- src/airflow/dags/combine_match_dag.py
spark에서 분석하기 위해 match/{date}/csv 파일들을 전부 합쳐서 merge_csv를 만드는 작업입니다.
- Related Issue #92 
- Closes #92
> feat: combine dag 생성

- src/airflow/dags/get_champion_tier_dag.py
- src/airflow/dags/get_riot_api_dag.py
- src/airflow/dags/transform_riot_data_dag.py
- src/airflow/dags/utils/common_util.py
- src/backend/app/models/mastery.py
- src/backend/app/models/summoner.py
- src/backend/app/routers/banpick.py
- src/backend/app/routers/mastery.py
배치 프로세스를 적용해 데이터 변환 시 강제 종료되는 현상을 해결했습니다.
black 포맷팅을 적용했습니다.
- Related Issue #87 
- Closes #
> fix: 데이터 변환 시 강제 종료 현상 해결

- src/backend/app/main.py
- src/backend/app/models/tier.py
- src/backend/app/routers/tier.py
- src/frontend/src/views/Banpick.vue
- tb_info 테이블 정보 가져오는 코드 추가
- Closes #
> Add functionality to fetch data from 'tb_info' table

- src/backend/app/main.py
- src/backend/app/routers/mastery.py
- src/backend/app/utils/helpers.py
불필요한 데이터베이스 쿼리를 줄이고 API 성능을 향상시키기 위해 in-memory 캐시를 적용했습니다.
mastery 엔드포인트를 캐싱하고, 캐시 만료 시간은 24시간으로 설정했습니다. 
```
pip install fastapi-cache2
```
- Closes #
> optimize: mastery 엔드포인트에 fastapi-cache2 적용

- docker-compose/docker-compose.yml
- src/airflow/dags/get_progamer_mastery_dag.py
- src/airflow/dags/utils/riot_util.py
- src/airflow/requirements.txt
- src/backend/app/main.py
- src/backend/app/routers/banpick.py
- src/backend/requirements.txt
챔피언 숙련도를 보고 유사한 프로게이머 찾는 기능입니다.
- Related Issue #106 
- Closes #106
소연님과 함께 PyCharm code with me로 개발했습니다.
> feat: 챔피언 숙련도를 보고 유사한 프로게이머 찾는 기능

- src/backend/app/models/tier.py
- src/backend/app/routers/tier.py
- src/frontend/src/components/ChampionButton.vue
- src/frontend/src/views/Banpick.vue
- 티어별로 챔피언들의 정보가 달라지게 하는 기능 추가
- 메인 페이지에 추천 챔피언 기능 추가
- Closes #
> feat: 티어별 챔피언 정보 추가

- src/backend/app/routers/banpick.py
- src/backend/app/routers/tier.py
- src/backend/requirements.txt
- src/frontend/src/views/Banpick.vue
- src/spark/spark-scripts/banpick_recommend.py
같은 호출에 대비하여 rds에 저장하긴 하나 사용자에게 4개의 쿼리를 기다리는것보다 나오는대로 알려주는게 낫다 판단하여
kinesis stream을 추가하였습니다.
- Closes #
> feat: emr에서 실시간으로 프론트에 보여지기 위해 kinesis stream 추가

- src/frontend/src/views/Banpick.vue
> fix: 티어 필터 스타일 오류 해결

- src/backend/app/routers/banpick.py
- src/frontend/src/views/Banpick.vue
> feat: 챔피언 분석 섹션 추가
